#Tomcat 服务
server:
  port: 8079

#shiro:
#  loginUrl: /login.html
#  # Let Shiro Manage the sessions
#  userNativeSessionManager: true
#  # disable URL session rewriting
#  sessionManager:
#    sessionIdUrlRewritingEnabled: false


spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC\u89E3\u51B3\u65F6\u533A\u7684\u62A5\u9519
    url: jdbc:mysql://localhost:3306/books?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置日志


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #日志

    map-underscore-to-camel-case: true  #开启自动驼峰命名规则（camel case）映射

    aggressive-lazy-loading: true #当设置为 true 的时候，懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载.
    lazy-loading-enabled: true #需要和 lazyLoadingEnabled 一起使用

    auto-mapping-behavior: partial #指定 MyBatis 是否并且如何来自动映射数据表字段与对象的属性
#    AutoMappingBehavior.NONE：不启用自动映射
#    AutoMappingBehavior.PARTIAL：只对非嵌套的 resultMap 进行自动映射
#    AutoMappingBehavior.FULL：对所有的 resultMap 都进行自动映射

    auto-mapping-unknown-column-behavior: none #指定 MyBatis 在自动映射过程中遇到未知列或者未知属性时如何处理
#    AutoMappingUnknownColumnBehavior.NONE：不做任何处理 (默认值)
#    AutoMappingUnknownColumnBehavior.WARNING：以日志的形式打印相关警告信息
#    AutoMappingUnknownColumnBehavior.FAILING：当作映射失败处理，并抛出异常和详细信息

    local-cache-scope: session
#    SESSION：session级别缓存，同一个session相同查询语句不会再次查询数据库
#    STATEMENT：关闭一级缓存

    cache-enabled: true #开启Mybatis二级缓存，默认为 true。

    call-setters-on-nulls: false #定当结果集中值为 null 的时候是否调用映射对象的 Setter（Map 对象时为 put）方法

    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler  #枚举

  mapper-locations: classpath*:**/mapper/xml/*.xml  #告诉 Mapper 所对应的 XML 文件位置

  type-aliases-package: com.saber.designjava.pojo #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名

  type-handlers-package: com.saber.designjava.type #会把该包下面的类注册为对应的 TypeHandler

  type-enums-package: com.saber.designjava.myenum #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性。

  check-config-location: false #启动时是否检查 MyBatis XML 文件的存在，默认不检查。

  executor-type: simple
#  ExecutorType.SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句（PreparedStatement）
#  ExecutorType.REUSE：该执行器类型会复用预处理语句（PreparedStatement）
#  ExecutorType.BATCH：该执行器类型会批量执行所有的更新语句
  global-config: #逻辑删除
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

##配置日期格式化的规则
#spring:
#  mvc:
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
#

#修改静态资源存放位置
#  resources:
#  static-locations:
#    classpath: /resources/static/

#关闭默认图标
#  spring.mvc.favicon.enabled=false